version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    volumes:
      - .:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    # The frontend is served by Nginx on port 80 inside the container (internal port).
    # This internal port 80 is mapped to port 3000 on the host machine.
    ports:
      - "3000:80"
